server.port=8888
spring.application.name=config-server
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Conexión a tu repositorio de GitHub
spring.cloud.config.server.git.uri=https://github.com/alexanderchicaiza07-byte/config-server-repo.git
spring.cloud.config.server.git.username=alexanderchicaiza07-byte
spring.cloud.config.server.git.password=token
spring.cloud.config.server.git.default-label=main

# Registro en Eureka (Puerto por defecto)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/