spring.application.name=categorias
server.port=0


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuraciones del nombre del archivo

eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
eureka.client.healthcheck.enabled=true

# 1. Prioridad: Importar la configuración del servidor
spring.config.import=optional:configserver:http://localhost:8888
# 2. Configuración para que busque el archivo en el Config Server
spring.cloud.config.uri=http://localhost:8888
# Esto hará que el microservicio falle rápido si no detecta el Config Server
spring.cloud.config.fail-fast=true


